# Generated by Django 5.0.4 on 2024-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hero_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
