# Generated by Django 5.0.4 on 2024-05-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_service_hero_description_alter_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images"),
        ),
    ]
