# Generated by Django 5.0.4 on 2024-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_service_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
