# Generated by Django 5.0.4 on 2024-05-01 21:19

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(upload_to=gallery.models.gallery_image_path),
        ),
    ]
