# Generated by Django 5.0.4 on 2024-05-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_image_image_file"),
        ("service", "0004_service_service_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_galleries",
                to="service.service",
            ),
        ),
    ]
